enquetes_snt/enigmes/urls.py
from django.urls import path
from .views import (
    EnigmeListView,
    EnigmeDetailView,
    EnigmeCreateView,
    EnigmeExampleCreateView,
    EnigmeUpdateView,
    enquete_informations,
)

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('accueil/', views.accueil, name='accueil'),
    path('enseignants/', views.enseignants, name='enseignants'),
    path('enigmes/', EnigmeListView.as_view(), name='enigmes'),
    path('enigme/<int:pk>/', EnigmeDetailView.as_view(), name='enigme-detail'),
    path('enigme/<int:pk>/modification/', EnigmeUpdateView.as_view(), name='enigme-update'),
    path('enigme/creation/', EnigmeCreateView.as_view(), name='enigme-create'),
    path('enigme/creation/exemple/', EnigmeExampleCreateView.as_view(), name='enigme-example-create'),
    path('enquete/informations/', views.enquete_informations, name='enquete-informations'),
    path('enquete/<int:enquete_id>/', views.enquete, name='enquete-detail'),
    path('enquete/<int:enquete_id>/suppression', views.suppression_enquete, name='enquete-delete'),
    path('enquete/<int:enquete_id>/resultats/', views.resultats_enquete, name='enquete-resultats'),
    path('enquete/<int:enquete_id>/maj-resultats/', views.maj_resultats, name='maj-resultats'),
    path('enquete/creation/', views.creation_enquete, name='enquete-create'),
    path('enquete/creation/liste/', views.creation_enquete_liste, name='enquete-liste-create'),
    path('enquete/creation/manuelle/', views.creation_enquete_manuelle, name='enquete-manuelle-create'),
    path('enquete/<int:enquete_id>/modification/', views.modification_enquete, name='enquete-modification'),
    path('enquete/<int:enquete_id>/modification/manuelle/', views.modification_enquete_manuelle, name='enquete-manuelle-modification'),
    path('enquete/<int:enquete_id>/modification/liste/', views.modification_enquete_liste, name='enquete-liste-modification'),
    path('enquete/partage/<str:code_enquete>/', views.partage_enquete, name='partage-enquete'),
    path('mon-espace/', views.espace_perso, name='espace-perso'),
    path('mon-espace/mes-enigmes/', views.mes_enigmes, name='mes-enigmes'),
    path('mon-espace/mes-fichiers/', views.mes_fichiers, name='mes-fichiers'),
    path('eleve/enquete/<str:code_enquete>/', views.eleve, name='enquete-eleve'),
    path('conditions/', views.conditions, name='cgu'),
]

enquetes_snt/enquetes_snt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('enigmes.urls')),
    path('enseignants/', include('enseignants.urls')),
    path('perso/', admin.site.urls),  
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

enquetes_snt/enigmes/models.py
from django.db import models
from django.db.models.fields import DateTimeField
from django.db.models.fields.related import ForeignKey
from django.utils import timezone
from django.conf import settings
from django.urls import reverse
from django.http import HttpResponse
from django import forms
from django.utils.functional import cached_property
from enigmes.validators import FileValidator
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _

import random, os
import ast
import pytz
import csv
import json
import datetime

class Fichier(models.Model):
    
    def repertoire_fichiers_auteur(instance, nom_fichier):
        # le fichier sera uploadé dans MEDIA_ROOT/auteur_<id>/<nom_fichier>
        return 'auteur_{0}/fichiers/{1}'.format(instance.auteur.id, nom_fichier)
    
    fichier = models.FileField(
        "Sélectionner un fichier",
        blank=False,
        max_length=100,
        upload_to=repertoire_fichiers_auteur,
        validators=[
            FileValidator(
                max_size=1024 * 1000, # 1 Mio
                content_types=(
                    'text/csv',
                    'application/vnd.oasis.opendocument.spreadsheet',  #.ods
                    'application/vnd.ms-excel',  #.xls
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',  #.xlsx
                    'text/x-python',  #.py
                    'text/html',
                    'text/css',
                    'text/plain', #.txt
                    'application/json',
                    'image/jpeg',
                    'image/png',
                )
            )
        ]
    )

    auteur = models.ForeignKey(settings.AUTH_USER_MODEL, models.SET_NULL, blank=True, null=True)  # si un utilisateur supprime son compte, ses fichiers restent
    
    @property
    def url(self):
        return self.fichier.url

    def __str__(self):
        return os.path.basename(self.fichier.name)

class Image(models.Model):
    
    def repertoire_images_auteur(instance, nom_fichier):
        # le fichier sera uploadé dans MEDIA_ROOT/auteur_<id>/<nom_fichier>
        return 'auteur_{0}/images/{1}'.format(instance.auteur.id, nom_fichier)
    
    image = models.ImageField(
        "Sélectionner une image",
        blank=False,
        max_length=100,
        upload_to=repertoire_images_auteur,
        validators=[
            FileValidator(
                max_size=1024 * 300, # 300 Kio
                content_types=(
                    'image/jpeg',
                    'image/png',
                )
            )
        ]
    )

    auteur = models.ForeignKey(settings.AUTH_USER_MODEL, models.SET_NULL, blank=True, null=True)  # si un utilisateur supprime son compte, ses fichiers restent

    @property
    def name(self):
        return os.path.basename(self.image.name)

    @property
    def url(self):
        return self.image.url

    def __str__(self):
        return os.path.basename(self.image.name)

def generer_code_enquete_unique():
    enquetes = Enquete.objects.all()
    codes_existants = set(enquete.code for enquete in enquetes)
    carac = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
    code = "".join(random.choices(carac, k=8))
    while code in codes_existants:
        code = "".join(random.choices(carac, k=8))
    return code

class Enigme(models.Model):
    class Theme(models.TextChoices):
        NC = 'NC', _('Non défini')
        INT = 'INT', _('Internet')
        WEB = 'WEB', _('Le Web')
        RS = 'RS', _('Les réseaux sociaux')
        DATA = 'DATA', _('Les données structurées et leur traitement')
        LCM = 'LCM', _('Localisation, cartographie, mobilité')
        IEOC = 'IEOC', _('Informatique embarquée et objets connectés')
        IMG = 'IMG', _('La photographie numérique')
        PY = 'PY', _('Python')
    
    date_creation = models.DateTimeField('date de création', auto_now_add=True)
    date_modification = models.DateTimeField('date de modification', default=timezone.now)
    auteur = models.ForeignKey(settings.AUTH_USER_MODEL, models.SET_NULL, blank=True, null=True)  # si un utilisateur supprime son compte, ses énigmes restent
    theme = models.CharField(
        'thème',
        max_length=4,
        choices=Theme.choices,
        default=Theme.NC
    )

    question_libre = models.BooleanField('Réponse libre attendue', default=False)
    
    enonce = models.TextField('énoncé')
    reponse = models.CharField('réponse', max_length=100, blank=True, null=True)
    reponse2 = models.CharField('réponse 2', max_length=100, blank=True, null=True)
    reponse3 = models.CharField('réponse 3', max_length=100, blank=True, null=True)
    reponse4 = models.CharField('réponse 4', max_length=100, blank=True, null=True)
    indication = models.TextField('indication', blank=True, null=True)
    commentaires = models.TextField('commentaires', blank=True, null=True)
    reponse_libre = models.TextField('réponse libre', blank=True, null=True)

    def repertoire_auteur(instance, nom_fichier):
        # le fichier sera uploadé dans MEDIA_ROOT/auteur_<id>/<nom_fichier>
        return 'auteur_{0}/{1}'.format(instance.auteur.id, nom_fichier)
    
    image = models.ForeignKey(Image, related_name='enigme', blank=True, null=True,on_delete=models.SET_NULL)
    
    """ image = models.ImageField(
        "Téléverser une image d'illustration",
        blank=True,
        max_length=100,
        upload_to=repertoire_auteur,
        validators=[
            FileValidator(
                max_size=1024 * 300, # 300 Kio
                content_types=(
                    'image/jpeg',
                    'image/png',
                )
            )
        ]
    ) """

    url_image = models.URLField("URL de l'image d'illustration", blank=True, null=True)

    credits_image = models.TextField("Crédits de l'image", blank=True, null=True)

    fichier = models.ForeignKey(Fichier, related_name='enigme', blank=True, null=True,on_delete=models.SET_NULL)

    """ fichier = models.FileField(
        "Fichier en pièce jointe",
        blank=True,
        max_length=100,
        upload_to=repertoire_auteur,
        validators=[
            FileValidator(
                max_size=1024 * 1000, # 1 Mio
                content_types=(
                    'text/csv',
                    'application/vnd.oasis.opendocument.spreadsheet',  #.ods
                    'application/vnd.ms-excel',  #.xls
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',  #.xlsx
                    'text/x-python',  #.py
                    'text/html',
                    'text/css',
                    'text/plain', #.txt
                    'application/json',
                    'image/jpeg',
                    'image/png',
                )
            )]
        ) """

    def __str__(self):
        return str(self.id) + " / " + str(self.auteur)
    
    def get_absolute_url(self):
        return reverse('enigme-detail', kwargs={'pk': self.pk})

    def liste_reponses(self):
        # si enigme classique
        if not self.question_libre:
            lst = [self.reponse]
            for r in [self.reponse2, self.reponse3, self.reponse4]:
                if r is not None:
                    lst.append(r)
            return [reponse_nettoyee(rep) for rep in lst]
        # sinon si énigme à réponse libre
        else:
            return [self.reponse_libre]

    class Meta:
        verbose_name = 'énigme'


class Enquete(models.Model):
    description = models.CharField('description', max_length=100, default='')  # ne sert que pour l'auteur
    date_creation = models.DateTimeField('date de création', auto_now_add=True)
    active = models.BooleanField('active', default=True)
    indications = models.BooleanField('indications', default=True)  # indications affichées par défaut
    score =  models.BooleanField('score', default=True)  # scores affichés après l'enquête par défaut
    correction = models.BooleanField('correction', default=False)  # reponses non affichées après l'enquête par défaut
    ordre_aleatoire = models.BooleanField('ordre aléatoire des énigmes', default=False)  # pas d'ordre aléatoire des énigmes par défaut
    auteur = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)  # si un utilisateur supprime son compte, ses enquêtes sont supprimées
    enigmes = models.ManyToManyField(Enigme, related_name='enigmes', blank=True)
    cle = models.CharField('clé', max_length=200, default='')
    code = models.CharField(
        "code de l'enquête",
        max_length=10,
        unique=True,
        null=True,
        default=generer_code_enquete_unique
    )

    @cached_property 
    def liste_enigmes_ordre_initial(self):
        '''on se base sur la clé pour avoir l'ordre'''
        liste_num_enigmes = self.cle.split(";")
        liste_enigmes = []
        for num_enigme in liste_num_enigmes:
            enigme = Enigme.objects.select_related('auteur', 'image', 'fichier').get(pk=int(num_enigme))
            liste_enigmes.append(enigme)
        return liste_enigmes
    
    @cached_property 
    def liste_enigmes(self):
        import random
        L = list(self.enigmes.all())
        if not self.ordre_aleatoire:
            return L
        else:
            random.shuffle(L)  # mélange en place
            return L
    
    @cached_property 
    def liste_numeros_enigmes_ordre_initial(self):
        liste_num_enigmes = self.cle.split(";")
        return [int(num) for num in liste_num_enigmes]

    @cached_property
    def liste_numeros_enigmes(self):
        return [enigme.pk for enigme in self.liste_enigmes]
    
    def creation_cle_enquete(self):
        enquete = Enquete.objects.get(pk=self.pk)
        liste_enigmes = enquete.liste_enigmes
        liste_num_enigmes = [str(enigme.pk) for enigme in liste_enigmes]
        cle = ";".join(liste_num_enigmes)
        self.cle = cle

enquetes_snt/enigmes/templates/enigmes/base_coloree.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'enigmes/css/base_coloree.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'enigmes/css/prism.css' %}" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- Loading mathjax macro -->
    <!-- Load mathjax -->
    <script type="text/javascript" async
      src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML">
      </script>
      <script type="text/x-mathjax-config">
  	MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']],
                                displayMath: [ ['$$','$$'], ["\\[","\\]"] ]}});
  	</script>
  </head>
  <body>
      <div class="header-container">
        <nav class="nav">
            <ul class="menu">
              {% if user.is_authenticated %}
                <li><a href="{% url 'accueil' %}">Accueil</a></li>
                <li><a href="{% url 'enigmes' %}">Énigmes</a></li>
                <li><a href="{% url 'enigme-create' %}">Créer une énigme</a></li>
                <li class="gauche"><a href="{% url 'espace-perso' %}">Espace personnel</a></li>                
                <li class="droite username">{{user.get_username}}</li>
                <li><a href="{% url 'logout'%}?next=/">Se déconnecter</a></li>
              {% else %}
                <li class="droite"><a href="{% url 'login'%}">Se connecter</a></li>
                <li><a href="{% url 'inscription'%}">S'inscrire</a></li>
              {% endif %}
            </ul>
        </nav>
      </div>

      <div class="content-wrapper">
        <div class="alert-container">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        </div>
        <div class="content-container">
          {% block content %}{% endblock %}
        </div>      
      </div>
      
      <footer>
        <div>
            Footer
        </div>
    </footer>

    <div class="js-files">
      <!-- Prism (code highlighter)-->
      <script src="{% static 'enigmes/js/prism.js' %}"></script>

      <!-- jQuery -->
      <script src="{% static 'enigmes/js/jquery.js' %}"></script>

      <!-- Bootstrap Core JavaScript -->
      <script src="{% static 'enigmes/js/bootstrap.min.js' %}"></script>
    </div>

  </body>
</html>

enquetes_snt/enigmes/templates/enigmes/boutons_scroll.html
<div id ="boutons-scroll">
    <div class="btn-scroll" id="btn-scroll-haut">
        <svg id="btn-haut" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 115.4 122.88"><title>up-arrow</title><path d="M24.94,67.88A14.66,14.66,0,0,1,4.38,47L47.83,4.21a14.66,14.66,0,0,1,20.56,0L111,46.15A14.66,14.66,0,0,1,90.46,67.06l-18-17.69-.29,59.17c-.1,19.28-29.42,19-29.33-.25L43.14,50,24.94,67.88Z"/></svg>
    </div>
    <div class="btn-scroll" id="btn-scroll-bas">
        <svg id="btn-bas" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 115.4 122.88"><title>down-arrow</title><path d="M24.94,55A14.66,14.66,0,0,0,4.38,75.91l43.45,42.76a14.66,14.66,0,0,0,20.56,0L111,76.73A14.66,14.66,0,0,0,90.46,55.82l-18,17.69-.29-59.17c-.1-19.28-29.42-19-29.33.24l.29,58.34L24.94,55Z"/></svg>
    </div>
</div>

{% load static %}
<script src="{% static 'enigmes/js/boutons_scroll.js' %}"></script>

enquetes_snt/enigmes/templates/enigmes/enigme.html
<div class="enigme">
    {% load markdownify %}
    {% load static %}
    {% load custom_tags %}
    
    <div class="enigme-metadata">
        {% if not pour_eleves %}
            <div class="metadata">
                <h2 class="num-enigme"><a class="lien-detail" href="{% url 'enigme-detail' enigme.id %}">Énigme n° {{ enigme.pk }}</a></h2>
                <small class="theme-enigme">{{ enigme.get_theme_display }}</small>
                {% if enigme.auteur == user %}
                    <a class="btn-modif" href="{% url 'enigme-update' enigme.id %}">Modifier l'énigme</a>
                {% endif %}
                <small class="auteur">
                    <img class="icone-auteur dim-fixe" src="{% static 'enigmes/img/avatar.svg' %}" alt="icone avatar profil">
                    {{ enigme.auteur.first_name }} {{ enigme.auteur.last_name|lower|capfirst }}
                </small>
                <small class="date-ajout">
                    <img class="icone-date dim-fixe" src="{% static 'enigmes/img/clock-line.svg' %}" alt="icone avatar profil">
                    {{ enigme.date_creation|date:"d F Y" }}
                </small>
            </div>            
        {% else %}
            <div class="metadata">
                <h2 class="num-enigme">Énigme n° {{ forloop.counter }}</h2>
                <p class="theme-enigme">{{ enigme.get_theme_display }}</p>
            </div>
        {% endif %}
    </div>
    <div class="enigme-image">
        {% if enigme.url_image %}
            <img class="centre image-responsive agrandir" src="{{ enigme.url_image }}" alt="illustration énigme">
            {% if enigme.credits_image %}
                <div class="apercu-credits-image">
                    <span>Crédits :</span>
                    <div class="credits-image">
                        {{ enigme.credits_image|markdownify }}
                    </div>
                </div>
            {% endif %}
        {% elif enigme.image %}
            <img class="centre image-responsive agrandir" src="{{ enigme.image.image.url }}" alt="illustration énigme">
            {% if enigme.credits_image %}
                <div class="apercu-credits-image">
                    <span>Crédits :</span>
                    <div class="credits-image">
                        {{ enigme.credits_image|markdownify }}
                    </div>
                </div>
            {% endif %}
        {% else %}
            {% include 'enigmes/img-theme.html' with theme=enigme.theme %}
        {% endif %}
    </div>
    <div class="enigme-enonce">
        {{ enigme.enonce|markdownify }}
    </div>
    {% if enigme.fichier %}
    <div class="piece-jointe">
        <svg class="icone" id="file-download" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 113.79 122.88"><defs><style>.cls-1{fill-rule:evenodd;}</style></defs><title>download-file</title><path class="cls-1" d="M65.59,67.32h38.82a9.41,9.41,0,0,1,9.38,9.38v36.79a9.41,9.41,0,0,1-9.38,9.39H65.59a9.41,9.41,0,0,1-9.38-9.39V76.7a9.41,9.41,0,0,1,9.38-9.38ZM60,11.56,79.73,30.07H60V11.56ZM20.89,70a2.14,2.14,0,0,0-2,2.23,2.1,2.1,0,0,0,2,2.22H45.67V70Zm0,16a2.14,2.14,0,0,0-2,2.23,2.1,2.1,0,0,0,2,2.23H45.67V85.91Zm0-47.89a2.14,2.14,0,0,0-2,2.23,2.11,2.11,0,0,0,2,2.23H43.81a2.14,2.14,0,0,0,2-2.23,2.11,2.11,0,0,0-2-2.23Zm0-16a2.14,2.14,0,0,0-2,2.23,2.1,2.1,0,0,0,2,2.23h12.6a2.14,2.14,0,0,0,2-2.23,2.11,2.11,0,0,0-2-2.23Zm0,31.93a2.14,2.14,0,0,0-2,2.23,2.12,2.12,0,0,0,2,2.23H59.65a2.14,2.14,0,0,0,2-2.23,2.1,2.1,0,0,0-2-2.23ZM90.72,32.72a3.28,3.28,0,0,0-2.39-3.17L59.23,1.21A3.27,3.27,0,0,0,56.69,0H5.91A5.91,5.91,0,0,0,0,5.91V107.12A5.91,5.91,0,0,0,5.91,113H45.76v-6.6H6.61V6.57H53.37V33.36a3.32,3.32,0,0,0,3.32,3.31H84.12V58.29h6.6V32.72Zm6.45,60.62a2.4,2.4,0,0,1,2.06,1c1.08,1.62-.4,3.22-1.42,4.35-2.91,3.19-9.49,9-10.92,10.66a2.37,2.37,0,0,1-3.72,0c-1.49-1.73-8.43-7.86-11.19-11-1-1.08-2.15-2.56-1.15-4a2.42,2.42,0,0,1,2.07-1h5.17V84.07A2.92,2.92,0,0,1,81,81.15H89.1A2.92,2.92,0,0,1,92,84.07v9.27Z"/></svg>
        <span class="texte-pj">Fichier à télécharger : </span>
        <a id="fichier" href="{{enigme.fichier.url}}" target="_blank" download="">   
            <span id="nom-fichier">{{enigme.fichier.fichier|filename}}</span>
        </a>
    </div>
    {% else %}
    <div class="piece-jointe vide">
    </div>
    {% endif %}
    {% if not pour_eleves %}
        {% if enigme.indication != '' %}
            <blockquote class="enigme-indication">
                    <img class="dim-fixe" src="{% static 'enigmes/img/info.svg' %}" alt="logo indication" width="30" height="30">
                {% autoescape off %}
                    <div>
                        {{ enigme.indication|markdownify }}
                    </div>
                {% endautoescape %}
            </blockquote>                    
        {% endif %}
    {% else %}
        {% if enigme.indication != '' and indications_activees %}
        <blockquote class="enigme-indication">
                <img class="dim-fixe" src="{% static 'enigmes/img/info.svg' %}" alt="logo indication" width="30" height="30">
            {% autoescape off %}
                <div>
                    {{ enigme.indication|markdownify }}
                </div>
            {% endautoescape %}
        </blockquote>                    
        {% endif %}
    {% endif %}
    {% if affiche_reponses %}
        <div class="enigme-reponse">
            
            {% if enigme.question_libre %}
            <div id="warning-reponse-libre">
                <span class="reponse-libre">
                    <?xml version="1.0" encoding="utf-8"?><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="122.88px" height="122.88px" viewBox="0 0 122.88 122.88" enable-background="new 0 0 122.88 122.88" xml:space="preserve"><g><path fill-rule="evenodd" clip-rule="evenodd" d="M61.44,0c33.926,0,61.44,27.514,61.44,61.44c0,33.926-27.514,61.439-61.44,61.439 C27.513,122.88,0,95.366,0,61.44C0,27.514,27.513,0,61.44,0L61.44,0z M52.687,90.555H69.44v14.81H52.687V90.555L52.687,90.555z M69.431,82.96H52.691c-1.665-20.343-5.159-29.414-5.159-49.729c0-7.492,6.075-13.57,13.567-13.57s13.57,6.078,13.57,13.57 C74.67,53.535,71.13,62.633,69.431,82.96L69.431,82.96z"/></g></svg>
                    Réponse libre attendue
                </span>
            </div>
            {% endif %}
            <details>
                <summary>
                    <span class="voir-reponse">Voir la réponse</span>
                </summary>
                    {% if not enigme.question_libre %}
                        <p>Réponse attendue : <span class="reponse-attendue">{{ enigme.reponse }}</span></p>
                        {% if enigme.reponse2 %}
                        <p>Autre(s) réponse(s) acceptée(s) : <span class="autre-reponse-acceptee">{{ enigme.reponse2 }}</span>{% if enigme.reponse3%}, <span class="autre-reponse-acceptee">{{ enigme.reponse3 }}</span>{% endif %}{% if enigme.reponse4%}, <span class="autre-reponse-acceptee">{{ enigme.reponse4 }}</span>{% endif %}</p>
                        {% endif %}
                    {% else %}
                        <div class="reponse-libre-attendue">
                            {% autoescape off %}
                            {{ enigme.reponse_libre|markdownify }}
                            {% endautoescape %}
                        </div>
                    {% endif %}
                {% if enigme.commentaires %}                
                <div id="para-commentaires">
                    <span>Commentaire</span>
                    {% autoescape off %}
                    {{ enigme.commentaires|markdownify }}
                    {% endautoescape %}
                </div>
                {% endif %}
            </details>
        </div>
    {% elif zone_saisie_reponses %}
        {% if not apercu_reponses %}
        <div class="zone-reponse">
            {% for field in form %}
                {% if field.name == enigme.pk|stringformat:"i" %}
                    {{ field.errors }}
                    <p>
                        {{ field.label_tag }}
                    </p>
                    <p>
                        {{ field }}
                    </p>                    
                {% endif %}
            {% endfor %}
        </div>
        {% else %}
        <div class="zone-reponse">
            <p>
                <label for="{{enigme.pk}}">Réponse :</label>
            </p>
            <p>
                {% if not enigme.question_libre %}
                <input type="text" name="{{enigme.pk}}">
                {% else %}
                <textarea name="{{enigme.pk}}" placeholder="Répondre par une (ou plusieurs) phrase(s)." cols="40" rows="10"></textarea>
                {% endif %}
            </p>
        </div>
        {% endif %}
    {% endif %}
</div>

enquetes_snt/enigmes/templates/enigmes/enigme_detail.html
{% extends 'enigmes/base.html' %}

{% block nav %}
{% include 'enigmes/nav.html' with nav="nav_complete" %}
{% endblock %}

{% block content %}
{% include 'enigmes/modale_images.html' %}
{% load static %}
{% load custom_tags %}
    <div class="enigme-container">
        {% include 'enigmes/enigme.html' with enigme=enigme pour_eleves=False affiche_reponses=True%}
    </div> 


{% endblock %}

{% block jsfiles %}
{% load static %}
<script src="{% static 'enigmes/js/gestion_images_liens.js' %}"></script>
<script src="{% static 'enigmes/js/prism.js' %}"></script>
{% endblock %}

enquetes_snt/enigmes/templates/enigmes/img-theme.html
{% load static %}
{% if theme == "INT" %}
    <object class="icone-theme centre" type="image/svg+xml" data="{% static 'enigmes/img/theme-int.svg' %}"></object>
{% elif theme == "WEB" %}
    <object class="icone-theme centre" type="image/svg+xml" data="{% static 'enigmes/img/theme-web.svg' %}"></object>
{% elif theme == "RS" %}
    <object class="icone-theme centre" type="image/svg+xml" data="{% static 'enigmes/img/theme-rs.svg' %}"></object>
{% elif theme == "DATA" %}
    <object class="icone-theme centre" type="image/svg+xml" data="{% static 'enigmes/img/theme-data.svg' %}"></object>
{% elif theme == "LCM" %}
    <object class="icone-theme centre" type="image/svg+xml" data="{% static 'enigmes/img/theme-lcm.svg' %}">
    </object>
{% elif theme == "IEOC" %}
    <object class="icone-theme centre" type="image/svg+xml" data="{% static 'enigmes/img/theme-ieoc.svg' %}"></object>
{% elif theme == "IMG" %}
    <object class="icone-theme centre" type="image/svg+xml" data="{% static 'enigmes/img/theme-img.svg' %}"></object>
{% elif theme == "PY" %}
    <object class="centre" type="image/svg+xml" data="{% static 'enigmes/img/python-logo.svg' %}"></object>
{% endif %}